services:
  server:
    image: localhost:5000/requestobot:latest
    build: .
    restart: unless-stopped
#    networks:
#      - proxynet
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./twitch_token.json:/usr/src/app/twitch_token.json

  db:
    image: localhost:5000/requestobot-db:latest
    build: docker/db
    restart: always
    ports:
      - 5432:5432 # FIXME: Remove for actual deployment
    volumes:
      - requestobot-pgdata:/var/lib/postgresql/data
      - ./dumps:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}

#networks:
#  proxynet:
#    name: nextcloud-docker_proxy-tier
#    external: true
volumes:
  requestobot-pgdata:
