export const SONG_IMPORTERS = 'SONG_IMPORTERS';
export const SONG_SEARCH_STRATEGIES = 'SONG_SEARCH_STRATEGIES';
export const MOD_IO_API_KEY = 'MOD_IO_API_KEY';
export const MOD_IO_BASE_URL = 'MOD_IO_BASE_URL';
export const TRIPPY_TUNES_BASE_URL = 'TRIPPY_TUNES_BASE_URL';
export const YTDLP_PATH = 'YTDLP_PATH';
export const DOWNLOADED_SONGS_PATH = 'DOWNLOADED_SONGS_PATH';
export const STATIC_SITE_BASE_URL = 'STATIC_SITE_BASE_URL';
