sequenceDiagram
  client ->> server: /api/users?self=true
  alt no jwt
  server ->> client: 401 Not Authorized
  end
  alt jwt expired
  server ->> client: 403 Forbidden?
  end
  client ->> server: /api/jwt-refresh
