export const STEAM_APIKEY = 'STEAM_APIKEY';
export const BASE_URL = 'BASE_URL'; // The base URL to use when constructing URLs - used in SSO return urls.
export const JWT_SECRET = 'JWT_SECRET';
export const JWT_COOKIE_NAME = 'JWT_COOKIE_NAME';
export const JWT_EXPIRE_TIME = 'JWT_EXPIRE_TIME';
export const REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET';
export const REFRESH_TOKEN_COOKIE_NAME = 'REFRESH_TOKEN_COOKIE_NAME';
export const REFRESH_TOKEN_EXPIRE_TIME = 'REFRESH_TOKEN_EXPIRE_TIME';

export const TWITCH_CLIENT_ID = 'TWITCH_CLIENT_ID';
export const TWITCH_CLIENT_SECRET = 'TWITCH_CLIENT_SECRET';

export const AUTH_CODE_EXPIRE_TIME_MS = 'AUTH_CODE_EXPIRE_TIME_MS';
export const STATE_VALUE_EXPIRE_TIME_MS = 'STATE_VALUE_EXPIRE_TIME_MS';
